version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: mike3983.reverseproxy
  backend_user:
    build:
      context: ../../udagram-api-user
    image: mike3983/udagram-api-user
  backend_feed:
    build:
      context: ../../udagram-api-feed
    image: mike3983/udagram-api-feed
  frontend:
    build:
      context: ../../udagram-frontend
    image: mike3983/udagram-frontend:local
